import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import { Header } from './components/ui/header';
import { Footer } from './components/ui/footer';

const inter = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Norte Sul Engenharia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
